# fly.toml app configuration file generated for kit300-p6 on 2025-04-29T00:13:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kit300-p6'
primary_region = 'syd'

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  protocol = "tcp"
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
